### ISSUE TITLE
Sign in with GitHub to access app

### ISSUE THREAD

**Issue by ameliejyc** [ameliejyc/prereq-check#8]
As a selection panel member I can login with my GitHub account to access the app.
As an applicant I can login with my GitHub account to access the app.

Acceptance criteria:

- [x] Sign in with GitHub button to log into the app

![login page with info](https://user-images.githubusercontent.com/14337958/30060023-7aa51d68-9239-11e7-8285-8c826b7326d8.png)

**Comment by BartBucknill** [comment]
I was a wondering how easy it would be to get the username of the signed in user from github oauth as I couldn't see it in the docs. I found [this stackoverflow question](https://stackoverflow.com/questions/33411062/find-out-username-after-user-has-logged-in-to-github-via-oauth2) which seems to provide the answer, basically making a call the github api with the access token from the login in order to get the username.

**Comment by dangerdak** [comment]
This is dependent on #10 - it isn't necessary unless that's done.

**Comment by dangerdak** [comment]
Something to decide on: [sessions vs authorization token](https://stackoverflow.com/a/21023225)
